name: bello
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.13
  isar: ^3.0.0
  isar_generator: ^3.1.0+1
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
